### ISSUE TITLE
Arreglar las imagenes

### ISSUE THREAD

**Issue by evening-hs** [Gspr-bit/IG-P1-Wikipedia-Scrapper#2]
Los links de las imagenes estan rotos. Hay que arreglarlas o quitarlas.

**Comment by Gspr-bit** [comment]
Resuelto en 
![image](https://github.com/Gspr-bit/IG-P1-Wikipedia-Scrapper/assets/65473884/9fc62539-98cc-43aa-a626-ef9e0aa2d3ff)

**Comment by Gspr-bit** [comment]
Resuelto en 8808f40

**Comment by evening-hs** [comment]
Resuelto en 8808f40
